### ISSUE TITLE
Stuck on 'prepping model...'

### ISSUE THREAD

**Issue by psx2** [NotNANtoN/diffusion_gen#2]
![1168](https://user-images.githubusercontent.com/77219161/150696890-5c0c2742-5771-40dd-96a6-3c9635578094.png)

I seem to be stuck here without any progress, any ideas?

**Comment by NotNANtoN** [comment]
Hi, first of all, referring to problems derived from issue #1 the package `ldm` from pip, rather it is a package in the "latent-diffusion" repository - which should be cloned correctly when using the newest version with `ipython3 diffuse.py`. So if you installed ldm then uninstall it again.

I never was stuck there - it might just take a longer while? If it runs for more than 30 mins then interrupt the process with `CTRL`+ `C` and show the output afterwards to see where it is stuck.

**Comment by psx2** [comment]
Thank you for the fast reply!

Was something on my end, managed to get it fixed by removing pytorch completely and installing cuda 11.3 drivers + corresponding pytorch drivers.
