### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll

### ISSUE THREAD

**Issue by Ideoken** [NotNANtoN/diffusion_gen#4]
Hello, thanks for your project, after the first generation, at the end of processing (250/250) i had this error message, but i am a very newbie in python so i don't really know what to do to fix it :

```
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.█████████████████████████████████████████████████████████████| 250/250 [05:20<00:00,  1.54s/it]
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

**Comment by NotNANtoN** [comment]
Hi, I googled your error message and found this page: https://stackoverflow.com/questions/20554074/sklearn-omp-error-15-initializing-libiomp5md-dll-but-found-mk2iomp5md-dll-a


They recommend to install the following if you are using anaconda:
`conda install nomkl`

If that does not work you can try to copy the following two lines to the very top of diffuse.py, save the file, then run it again:
`
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
`

Let me know if it works!

**Comment by Ideoken** [comment]
I added 
`os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"` on diffuse.py
And restarted my PC and i don't have this error message anymore.

**Comment by NotNANtoN** [comment]
Great! Closing this for now.
