### ISSUE TITLE
unrecognized arguments: --init_image

### ISSUE THREAD

**Issue by psx2** [NotNANtoN/diffusion_gen#5]
Hi,

I can't seem to get initial image to work, any ideas on where I'm going wrong?

**Comment by Ideoken** [comment]
I edited `diffuse.py` and added
`parser.add_argument("--init_image", default=None, type=str)`

After main arguments

And edited

`init_image = argparse_args.init_image #@param{type: 'string'}`

in the line 1135 or arround this

it work but i didnt noticed something special.

**Comment by NotNANtoN** [comment]
I added the `init_image` to the argparse now! You can also now modify `skip_steps` to determine how many steps the init_image is copied before fitting to the text prompt.
